
import { Teacher, Task, TaskCategory } from './types';

// Processed list of teachers from the provided text, PRESERVING ORDER for hierarchy
const TEACHER_NAMES = [
  "TERMEZI BIN JUSOH", "YUSPANI BIN YUSOF", "MOHD AZRI BIN ISMAIL", "MOHD HAFIZI BIN HAMZAH", "AZIZAN BIN HARUN", 
  "MOHD FADLY BIN THAYIL MAMMI", "WAN RAMLAH BINTI MAMAT", "MASNIZA BINTI AWANG @ ZAKARIA", "NUR IZYANI BINTI IBRAHIM", 
  "ROHAIZAH ROHANA BINTI JUSOH", "MOHD ABDUL AZIZ BIN MOHD GHAZALI", "MOHD RIDWAN BIN RAZALI", "ANNA JULIYANTI BINTI ZAINUDIN", 
  "NURLIANA BINTI ROMLI", "NURUL DIYANA BINTI MAT KASIM", "SUHARNI BT SAMARUDIN", "ADA'YA @ ZAKARIA BIN YASIN", 
  "ANUAR BIN JUSOH", "CHE MOHD SAKIMI BIN CHE HAMID", "WAN NASHRIAH BINTI WAN JUSOH", "WAN NORAZIHAH BINTI WAN IBRAHIM", 
  "MOHAMAD QAYYUM BIN MOHAMAD ROZLAN", "MUHAMMAD FAKHRI BIN RAMLEY", "SAJDAH BINTI EN. AZIZ", "FAIZO BIN ISMAIL", 
  "MUHAMMAD AFIQ BIN CHE LAH", "MUHAMMAD BADRUZZAMAN BIN HASSAN", "AIDAWATI BINTI TAJI MUHAMMAD", "HALISA BINTI MOHD DARUS", 
  "NOR SUZILAINI BINTI HUSAIN", "NOR ZAINE BINTI OTHMAN", "NORAINI BINTI MOHD NOR", "NORAISAH BINTI HASSAN", 
  "NORAZIZAH BINTI JUSOH", "NORHASLIZA BINTI MAT LAZIM", "NUR 'IZZATI BINTI AZIZ", "NUR SHEELLY SUHADA BINTI ABDUL RAZAK", 
  "NURUL FARIZAH BTE ALI", "NURUL NORLAILATUL NADIA BINTI JUHARI", "NURUL SALEHAH BINTI ABDUL WAHAB", "NURULHANI BINTI BAHARUDIN", 
  "RA'ANAH BT HUSAIN", "ROPIZA BINTI HASSAN", "SITI FATIMAH BINTI MOHAMAD ZAID", "SITI NORIHAN BINTI MAT HUSIN", 
  "SUHAILA BINTI SALLEH", "ZAHIDAH BINTI MOHAMAD AMIN", "ABDUL MUN'IM BIN MOHD MANSOR", "AHMAD FA'IZ BIN SHUKERI", 
  "AHMAD FUAD BIN MOHD ZANI", "AHMAD HUSAINI BIN MUSTAPHA KAMIL", "AHMAD NAIM BIN AHMAD LUTFI", "AHMAD NAJMI BIN MAT PIAH", 
  "AHMAD NAJMI BIN YUSOF", "AHMAD TARMIZI BIN CHE HAMID", "CHE FAIZUL AZHAR BIN CHE MAT", "MOHAMAD AIDIL AFIFI BIN LOKMAN", 
  "MOHAMED AYUB BIN GHAZALI", "MOHAMMAD FADHIL ZIKRI BIN BANIYAMI", "MOHAMMAD IKRAM BIN MOHD NOR", "MOHAMMAD NOR HISYAM BIN MOEN", 
  "MOHD AFIZUL BIN MOHD SUHAIMI", "MOHD FARHAN BIN ZA'IM", "MOHD FATHI YAKAN BIN ZAKARIA", "MOHD HAFEZ BIN IBRAHIM @ MUSA", 
  "MOHD HAFIZUDDIN BIN MOHD SIDEK", "MOHD SHAHIRIE BIN ISMAIL", "MOHD SYAHID AL AMIN BIN RAZALI", "MUHAMAD AQILA BIN YUSUF", 
  "MUHAMAD ZULHILMI BIN OTHMAN", "MUHAMMAD AFIQ BIN MD HADZIR", "MUHAMMAD AL AMIN SIDDIK BIN MOHMD NOR", "MUHAMMAD FADHIL BIN SHUIB", 
  "MUHAMMAD HANNAN BIN ABDUL BASIT", "MUHAMMAD MUKHLIS BIN SUHAIMI", "MUHAMMAD SOFUAN BIN ABD RAHIM", "NABIHAN ASYRAF BIN MAHMUD ZUHUDI", 
  "SUFYAN BIN OMAR", "SYAHMI ZAFRAN BIN SAIFUL YAZAN", "ZUL FAKAAR BIN MAT GHANI", "FARHATUL ATHIRAH BINTI ZAINI", "FASIHAH BINTI MOHD PAUZI", 
  "FATIHAH BINTI SALLEH", "HANA THARWAH BINTI ABDUL HADI", "NAHIDAH BINTI MAT NOR", "NAZIHA BINTI YUSOFF", "NIK NURZULAIKHA BINTI NIK ZULKIFLI", 
  "NOOR IZAYATIE BINTI MANSORDIN", "NOR SHOLEHAH BINTI MUHAMMAD ROSDI", "NUR FATHIHA BINTI RUSLI", "NURSHAMIMI BINTI MOHD RADZI", 
  "NURUL AISYAH FATEHA BT AHMAD", "ROSLINA BINTI RAMLI", "SHAFIDA BINTI OSMAN", "SITI AISHAH BINTI MOHD DAUD", "SITI ASMA' BINTI MOHAMED", 
  "SITI FARHANAH BINTI ZAKARIA", "SITI MARIAM BINTI MOHD BADRILLAH", "SITI NAZIHAH BINTI MOHAMAD YUSUF", "SITI NOR ASHMAA' BINTI MOHD HATTA", 
  "SITI NOR AZIZAH BINTI MOHD ALI", "SITI NUR SAKINAH JALILIY BINTI ABDUL MUTTALIB", "SITI SAMIHAH BINTI KHAMARULZAMAN", "SITI SHARAHAH BINTI MOHD SHAFUDDIN", 
  "SUMAYYAH BINTI MOKTAR", "SURIANI BINTI MUHAMED HASSIM", "TAYYIBAH BINTI ABD HALIM", "WAN NORBAINI BINTI WAN ROSLI", 
  "WAN NUR AMIRAH BINTI WAN MOHD GHAZALI", "WAN SALWA BINTI WAN HASSAN", "MOHD ZAWAWI BIN MAT NOOR"
];

// Generate Teachers with sequential IDs
export const INITIAL_TEACHERS: Teacher[] = TEACHER_NAMES.map((name, index) => ({
  id: (index + 1).toString(),
  name: name,
  position: (index === 0 ? 'PENGETUA' : index < 5 ? 'PENOLONG KANAN' : index < 12 ? 'GKMP/KETUA JABATAN' : 'GURU AKADEMIK'),
  department: 'AKADEMIK'
}));

export const AVAILABLE_YEARS = [2026];

// Specific roles requested by user - ALL UPPERCASE
export const TASK_ROLES = [
  "PENYELARAS",
  "PENOLONG PENYELARAS",
  "SETIAUSAHA",
  "PENOLONG SETIAUSAHA",
  "KETUA",
  "PENOLONG",
  "AJK",
  "PENGERUSI", 
  "TIMBALAN PENGERUSI", 
  "NAIB PENGERUSI", 
  "BENDAHARI", 
  "PENGURUS",
  "PEGAWAI ASET",
  "PENOLONG PEGAWAI ASET",
  "YANG DIPERTUA",
  "NAIB YANG DIPERTUA",
  "PENASIHAT",
  "JURU AUDIT",
  "GURU DATA",
  "MENTOR",
  "APPLE TEACHER",
  "LAIN-LAIN"
];

// Raw job scope data - CONVERTED TO UPPERCASE
const RAW_JOB_SCOPE: Record<TaskCategory, string[]> = {
  [TaskCategory.PENTADBIRAN]: [
    "PENGURUSAN TERTINGGI", "MAJLIS TADBIR", "PENGURUSAN PRESTASI (PBPPP DAN LNPT)", 
    "PENGURUSAN KEWANGAN & AKAUN", "PENGURUSAN ASET (JKPA)", "PENGURUSAN FIZIKAL & BILIK KHAS", 
    "BILIK MESYUARAT", "PEJABAT PENTADBIRAN", "BILIK GKMP", "BILIK ICIC", 
    "DEWAN ULUL ALBAB", "DEWAN KULIAH ULUL ALBAB", "BILIK GURU 1 – AKADEMIK (P)", 
    "BILIK GURU 2 - AKADEMIK (L)", "BILIK GURU 3 (KBT P)", "BILIK GURU 4 (SUUA)", 
    "BILIK GURU 5 (KBT L)", "BILIK GURU 6 (KBT L)", "PUSAT SUMBER SEKOLAH", 
    "SURAU AJWAD AJYAD", "BILIK BDK", "KOPERASI / KAFETERIA", "BILIK DISIPLIN", 
    "PEJABAT STOR", "MAKMAL SAINS", "MAKMAL KIMIA", "MAKMAL BIOLOGI", "MAKMAL FIZIK", 
    "MAKMAL KOMPUTER", "BILIK UJIAN SEGAK", "BILIK PEPERIKSAAN", "BILIK SUKAN", 
    "GELANGGANG PERMAINAN", "BENGKEL RBT/ERT", "PERABOT", "BILIK AKSES 1 & 2", 
    "STUDIO", "BILIK MATEMATIK", "LOBI & SPEAKER CORNER", "BILIK GERAKAN MPM", 
    "BILIK NILAM", "BILIK SEMINAR 1 & 2", "BILIK BOSS", "BILIK KEBUDAYAAN", 
    "BILIK KESIHATAN/ISOLASI", "BILIK PSV", "BILIK SEJ & GEOG", "BAS/VAN SEKOLAH", 
    "PENGURUSAN PEJABAT", "PENGURUSAN PERANCANGAN STRATEGIK ORGANISASI/ TS25 & REFORMASI SEKOLAH", 
    "SKPM KUALITI @ SEKOLAH (SK@S)", "PENGURUSAN KBAT", "KBAT DALAM KURIKULUM", 
    "KBAT DALAM PEDAGOGI", "KBAT DALAM PENTAKSIRAN", "KBAT DALAM KOKURIKULUM", 
    "KBAT DALAM SOKONGAN KOMUNITI & SWASTA", "KBAT DALAM BINA UPAYA", "KBAT DALAM SUMBER", 
    "KBAT DALAM PERSEKITARAN", "PENINGKATAN PROFESIONALISME & LADAP", "BUKU PENGURUSAN DAN TAKWIM SEKOLAH", 
    "BUKU PENGURUSAN", "TAKWIM SEKOLAH", "PENGURUSAN GURU BERTUGAS", "PENGURUSAN MESYUARAT GURU", 
    "PENGURUSAN DOKUMENTASI", "PENGURUSAN GALERI", "PENGURUSAN KAJIAN TINDAKAN DAN KAJIAN PENYELIDIKAN", 
    "KEBITARAAN SEKOLAH", "BIDANG I : INOVASI", "BIDANG II : HAFAZAN AL-QURAN", 
    "PENGURUSAN ICT", "PROGRAM GURU PENYAYANG", "PENGURUSAN BENCANA", 
    "PERSATUAN IBU BAPA DAN GURU (PIBG)", "PENGLIBATAN IBU BAPA DAN KOMUNITI (PIBK & PIBKS)", 
    "JALINAN & JARINGAN", "BUDAYA ALQURAN", "ECO-SCHOOL", "KELAB WARGA IBEST", 
    "MAJLIS GURU CEMERLANG IBEST", "PENGURUSAN DATA"
  ],
  [TaskCategory.KURIKULUM]: [
    "JAWATANKUASA KURIKULUM SEKOLAH (JKS)", "JAWATANKUASA PANITIA MATA PELAJARAN", 
    "BAHASA MELAYU", "KP BAHASA MELAYU", "SETIAUSAHA BAHASA MELAYU", 
    "BAHASA INGGERIS", "KP BAHASA INGGERIS", "SETIAUSAHA BAHASA INGGERIS", 
    "BAHASA MANDARIN", "KP BAHASA MANDARIN", "SEJARAH", "KP SEJARAH", "SETIAUSAHA SEJARAH", 
    "GEOGRAFI", "KP GEOGRAFI", "PENDIDIKAN SENI VISUAL", "KP PENDIDIKAN SENI VISUAL", 
    "SETIAUSAHA PSV", "PENDIDIKAN JASMANI & PENDIDIKAN KESIHATAN", 
    "KP PEN. JASMANI & PEN. KESIHATAN", "SETIAUSAHA PJPK", 
    "SAINS", "KP SAINS", "SETIAUSAHA SAINS", "MATEMATIK", "KP MATEMATIK", "SETIAUSAHA MATEMATIK", 
    "FIZIK", "KP FIZIK", "SETIAUSAHA FIZIK", "KIMIA", "KP KIMIA", "SETIAUSAHA KIMIA", 
    "BIOLOGI", "KP BIOLOGI", "SETIAUSAHA BIOLOGI", "MATEMATIK TAMBAHAN", 
    "KP MATEMATIK TAMBAHAN", "SETIAUSAHA MATEMATIK TAMBAHAN", 
    "REKA BENTUK TEKNOLOGI", "KP REKA BENTUK TEKNOLOGI", "SETIAUSAHA RBT", 
    "PRINSIP AKAUN", "KP PRINSIP AKAUN", "PENDIDIKAN ISLAM", "KP PENDIDIKAN ISLAM", 
    "SETIAUSAHA PENDIDIKAN ISLAM", "BAHASA ARAB", "KP BAHASA ARAB", "SETIAUSAHA BAHASA ARAB", 
    "I’DADI", "KP I’DADI", "SETIAUSAHA I'DADI", "HIFZ AL-QURAN", "KP HIFZ AL-QURAN", 
    "SETIAUSAHA HIFZ AL-QURAN", "MAHARAT AL-QURAN", "KP MAHARAT AL-QURAN", 
    "SETIAUSAHA MAHARAT AL-QURAN", "TURATH AL-QURAN & AL-SUNNAH", "KP TURATH AL-QURAN & AL-SUNNAH", 
    "SETIAUSAHA TURATH AL-QURAN & AL-SUNNAH", "TURATH BAHASA ARAB", "KP TURATH BAHASA ARAB", 
    "SETIAUSAHA TURATH BAHASA ARAB", "TURATH DIRASAT ISLAMIAH", "KP TURATH DIRASAT ISLAMIAH", 
    "SETIAUSAHA TURATH DIRASAT ISLAMIAH", "JAWATANKUASA PENCERAPAN KURIKULUM", 
    "JAWATANKUASA JADUAL WAKTU DAN GURU GANTI", "JAWATANKUASA PROJEK KECEMERLANGAN AKADEMIK", 
    "PROJEK KECEMERLANGAN SPM", "PROJEK KECEMERLANGAN PRA SPM", "PROJEK KECEMERLANGAN TINGKATAN 3", 
    "PROJEK KECEMERLANGAN TINGKATAN 2", "PROJEK KECEMERLANGAN TINGKATAN 1", 
    "JAWATANKUASA UNIT PENILAIAN DAN PEPERIKSAAN AWAM (SPM)", "JAWATANKUASA UNIT PENILAIAN DAN PEPERIKSAAN DALAMAN", 
    "PENTAKSIRAN BERASASKAN SEKOLAH (PBS)", "PENTAKSIRAN BILIK DARJAH (PBD)", 
    "UJIAN AKHIR SESI AKADEMIK (UASA)", "PENILAIAN SEGAK", "PENTAKSIRAN PAJSK", 
    "PENTAKSIRAN PSIKOMETRIK (PPSi)", "KURIKULUM BERSEPADU TAHFIZ (KBT)", 
    "HIFZ DAN MAHARAT TINGKATAN 1", "HIFZ DAN MAHARAT TINGKATAN 2", "HIFZ DAN MAHARAT TINGKATAN 3", 
    "HIFZ DAN MAHARAT TINGKATAN 4", "HIFZ DAN MAHARAT TINGKATAN 5", 
    "JAWATANKUASA PROGRAM MEMARTABATKAN BAHASA MELAYU DAN MEMPERKUKUHKAN BAHASA INGGERIS (MBMMBI)", 
    "JAWATANKUASA DUAL LANGUAGE PROGRAM (DLP)", "JAWATANKUASA PEMBELAJARAN ABAD KE-21 (PAK 21)", 
    "JAWATANKUASA ELEARNING", "DELIMA KPM", "APPLE CLASSROOM", "JAWATANKUASA PUSAT SUMBER & TEKNOLOGI PENDIDIKAN", 
    "PERPUSTAKAAN AL-IDRISI", "TEKNOLOGI PENDIDIKAN", "JAWATANKUASA PENGURUSAN MAKMAL SAINS", 
    "JAWATANKUASA PENGURUSAN MAKMAL KOMPUTER", "JAWATANKUASA PENGURUSAN BENGKEL RBT"
  ],
  [TaskCategory.HEM]: [
    "PENGURUSAN INDUK HAL EHWAL MURID", "PENGURUSAN DISIPLIN SEKOLAH", "KELAB PENCEGAHAN JENAYAH", 
    "PENGURUSAN MAJLIS KEPIMPINAN MURID (MPM)", "BADAN PERWAKILAN MURID (BPM)", 
    "BADAN PERWAKILAN ASRAMA (BPA)", "PEMBIMBING RAKAN SEBAYA (PRS)", 
    "BADAN DAKWAH & KEROHANIAN (BDK) (STRUKTUR BALIK MENGIKUT LAJNAH)", "PENGAWAS PUSAT SUMBER SEKOLAH (PSS)", 
    "PENGAWAS SKIM PINJAMAN BUKU TEKS (SPBT)", "BADAN PERWAKILAN KETUA KELAS", 
    "PENGURUSAN PENDAFTARAN MURID & MINGGU SIMULASI", "PENGURUSAN DATA MURID", "PENGURUSAN TINGKATAN", 
    "PENGURUSAN KECERIAAN, KESELAMATAN & KESIHATAN (3K)", "UNIT KECERIAAN", "UNIT KESELAMATAN", 
    "UNIT KESIHATAN", "PENGURUSAN SKIM PINJAMAN BUKU TEKS (SPBT)", "PENGURUSAN BIASISWA DAN KEBAJIKAN MURID", 
    "UNIT BIASISWA (BKP & BKYT)", "UNIT KEBAJIKAN", "UNIT BANTUAN AWAM PERSEKOLAHAN (BAP)", 
    "UNIT KUMPULAN WANG AMANAH PELAJAR MISKIN (KWAPM)", "UNIT TAKAFUL MURID", "PENGURUSAN BIMBINGAN DAN KAUNSELING", 
    "UNIT KELAB PPDA", "INTERVENSI KEHADIRAN MURID CICIR", "PENGURUSAN ASRAMA", "PENGURUSAN DEWAN MAKAN", 
    "PENGURUSAN IMARAH SURAU", "PENGURUSAN KAFETERIA", "PENGURUSAN BILIK DARJAH", 
    "PENGURUSAN SAHSIAH GEN-T SEJAHTERA DAN MFLS", "PENGURUSAN MAJALAH & BULETIN", 
    "MAJALAH IBEST", "BULETIN IBEST"
  ],
  [TaskCategory.KOKURIKULUM]: [
    "JAWATANKUASA KOKURIKULUM", "JAWATANKUASA SUKAN DAN PERMAINAN", "OLAHRAGA DAN MERENTAS DESA", 
    "PROGRAM SENAMROBIK", "KELAB 1M1S", "PINGPONG", "BOLA SEPAK (LELAKI)", "BOLA JARING", 
    "BADMINTON", "BOULES (PETANQUE)", "BOLA TAMPAR", "BOLA BALING", "SEPAK TAKRAW", "CATUR", 
    "MEMANAH", "RENANG", "SILAT", "TAEKWONDO GTF", "JAWATANKUASA UNIT BERUNIFORM", "PENGAKAP", 
    "PERSATUAN BULAN SABIT MERAH (PBSM)", "PERSATUAN PUTERI ISLAM", "KADET REMAJA SEKOLAH", 
    "KADET POLIS SEKOLAH", "JAWATANKUASA KELAB DAN PERSATUAN", "KELAB MANDARIN", 
    "KELAB KOMPUTER / ANIMASI / EGAMES", "KELAB KESENIAN & KEBUDAYAAN", 
    "KELAB PELANCONGAN KOPERASI SEKOLAH / K3P", "KELAB KEMBARA", "KAUNSELING DAN KERJAYA", 
    "KELAB BAHASA MELAYU", "KELAB BAHASA INGGERIS", "KELAB BAHASA ARAB", 
    "KELAB PENGGUNA / PERMODALAN NASIONAL BERHAD", "KELAB USAHAWAN MUDA (PUM)", 
    "KELAB NADI HUFFAZ / QURRA’", "KELAB FALAK", "JAWATANKUASA KOPERASI SM IMTIAZ BESUT BERHAD"
  ],
  [TaskCategory.ULUL_ALBAB]: [
    "JAWATANKUASA ULUL ALBAB", "JAWATANKUASA PROGRAM KHAS ASASI IMTIAZ ULUL ALBAB (TINGKATAN 1)", 
    "JAWATANKUASA PENGURUSAN FIRQAH", "JAWATANKUASA AKHI DAN UKHTI", 
    "JAWATANKUASA QURANIK (QURANIC MEMORIZING PROGRAMME)", "JAWATANKUASA ENSIKLOPEDIK (CURRICULUM INTEGRATION & MULTILINGUAL)", 
    "JAWATANKUASA IJTIHADIK (PROGRAM ELIT, PENGINTEGRASIAN TEKNOLOGI – STEM, SEM & INOVASI)", 
    "KELAB ULUL ALBAB (AVIONIK/DRONE/SOLARIK/FOTONIK)", "KELAB ELIT ROBOTIK", "KELAB ELIT BERKUDA", 
    "KELAB STEM / SEM/ INOVASI", "JAWATANKUASA PROGRAM KOMUNITI & KEMASYARAKATAN (OUTDOOR ACTIVITIES)", 
    "JAWATANKUASA PEMIKIR ANDALUSIA 2.0"
  ]
};

// Transform all job scopes to UPPERCASE (Redundant now but kept for safety)
export const STANDARD_JOB_SCOPE: Record<TaskCategory, string[]> = Object.entries(RAW_JOB_SCOPE).reduce((acc, [key, values]) => {
    acc[key as TaskCategory] = values.map(v => v.toUpperCase());
    return acc;
}, {} as Record<TaskCategory, string[]>);

// --- DATA SEEDING UTILITIES ---

const createTask = (teacherId: string, title: string, description: string, category: TaskCategory = TaskCategory.PENTADBIRAN, year: number = 2026): Task => {
  // Logic to separate Role from Description if provided in "Role. Description" format
  let role = "AJK";
  let finalDescription = description;

  const parts = description.split('. ');
  if (parts.length > 0) {
    const potentialRole = parts[0].trim();
    // Simple heuristic to detect role: length check and typical formatting
    if (potentialRole.length < 50 && (parts.length > 1 || description.endsWith('.'))) {
      role = potentialRole.replace(/\.$/, ''); // Remove trailing dot
      finalDescription = parts.slice(1).join('. ').trim();
    }
  }

  // Detect specific role codes from description
  if (description.includes("(GDM)")) {
    role = "GURU DATA";
  }

  // Fallback for empty descriptions
  if (!finalDescription && role !== description) {
    // Description was just the role
    finalDescription = ""; 
  }

  return {
    id: `task-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    teacherId,
    year,
    title: title.toUpperCase(), // FORCE UPPERCASE
    role: role.toUpperCase(), // FORCE UPPERCASE
    description: finalDescription.toUpperCase(), // FORCE UPPERCASE
    category,
    createdAt: new Date().toISOString(),
  };
};

export const INITIAL_TASKS: Task[] = [];
